services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/certs:/etc/nginx/certs:ro
    networks:
      - proxy-net

  docker-gen:
    image: docker/docker-gen:latest
    container_name: nginx_docker_gen
    restart: unless-stopped
    command: -notify-sighup nginx_proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      # Read-only access
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/html:/usr/share/nginx/html
    networks:
      - proxy-net

  certbot:
    image: certbot/certbot
    container_name: nginx_certbot
    volumes:
      - ./proxy/certs:/etc/letsencrypt
      - ./proxy/html:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  proxy-net:
    name: thusaa-nginx-proxy-net
